<?php
// $Id: labjs.module,v 1.10 2011/01/19 08:12:21 jcisio Exp $

/**
 * @file
 *   LABjs module
 */

define('LABJS_EXCLUDE', '// LABjs exclusion');
define('LABJS_QUEUE', '$LAB._q=[];$LAB.queue=function(){Array.prototype.push.apply($LAB._q,arguments);return this};$LAB.executeQueue=function(){var a=$LAB;for(var i=0,l=$LAB._q.length;i<l;i++){if(typeof $LAB._q[0]=="string"){a=a.script($LAB._q[0])}else if($LAB._q[0]===false){a=a.wait()}else{a=a.wait($LAB._q[0])}$LAB._q.shift()}$LAB._q=[]};');

// If we are in maintenance mode, hook_init() is not called.
// We don't want to do anything else, either.
if (defined('MAINTENANCE_MODE')) {
  define('LABJS_DISABLE', TRUE);
}

/**
 * Implements hook_init().
 */
function labjs_init() {
  // Loads our loader first
  drupal_add_js(labjs_get_path(), array('group' => JS_LIBRARY, 'weight' => -50, 'every_page' => 1, 'inline' => TRUE, 'preprocess' => FALSE));
}

/**
 * Implements hook_js_alter().
 */
function labjs_js_alter(&$javascript) {
  if (defined('LABJS_DISABLE')) {
    return;
  }

  $scripts = array();
  $files = array();
  $preprocess_js = (variable_get('preprocess_js', FALSE) && (!defined('MAINTENANCE_MODE') || MAINTENANCE_MODE != 'update'));
  // The index counter is used to keep aggregated and non-aggregated files in
  // order by weight.
  $index = 1;

  // Sorts the scripts into correct order
  // Drupal assigns different weight for each scripts, thus we can't determine
  // if two scripts can be executed in parallel. However, they are all loaded in
  // parallel.
  uasort($javascript, 'drupal_sort_css_js');

  // Provide the page with information about the individual JavaScript files
  // used, information not otherwise available when aggregation is enabled.
  $setting['ajaxPageState']['js'] = array_fill_keys(array_keys($javascript), 1);
  unset($setting['ajaxPageState']['js']['settings']);
  drupal_add_js($setting, 'setting');

  foreach ($javascript as $key => $item) {
    if (empty($item['inline'])) {
      if ($item['type'] == 'file' || $item['type'] == 'external') {
        if ($item['type'] == 'external' || !$item['preprocess'] || !$preprocess_js) {
          $src = $item['type'] == 'external' ? $item['data'] : file_create_url($item['data']);
          $scripts[$index++] = "\"$src\"";
        }
        else {
          $filekey = 'aggregate_' . $item['group'] . '_' . $item['every_page'] . '_' . $index;
          $scripts[$filekey] = '';
          $files[$filekey][$item['data']] = $item;
        }
        unset($javascript[$key]);
      }
    }
    elseif ($item['type'] == 'inline') {
      $javascript[$key]['data'] = LABJS_EXCLUDE . "\n" . $javascript[$key]['data'];
    }
  }

  // Aggregates any remaining JS files
  if ($preprocess_js && count($files) > 0) {
    foreach ($files as $key => $file_set) {
      $uri = drupal_build_js_cache($file_set);
      // Only include the file if was written successfully. Errors are logged
      // using watchdog.
      if ($uri) {
        $scripts[$key] = "\"" . file_create_url($uri) . "\"";
      }
    }
  }

  // Adds the JS function call
  $javascript['labjs'] = array(
    'scope' => 'header',
    'type' => 'inline',
    'data' => LABJS_EXCLUDE . "\n" . LABJS_QUEUE . "\$LAB.setGlobalDefaults({AlwaysPreserveOrder:true});\n\$LAB.queue(" . implode(")\n\$LAB.queue(", $scripts) . ");",
    'defer' => FALSE,
    'group' => JS_LIBRARY,
    'every_page' => 1,
    'weight' => -20,
  );
  $javascript['labjs-footer'] = array(
    'scope' => 'footer',
    'type' => 'inline',
    'data' => LABJS_EXCLUDE . "\n\$LAB.executeQueue();",
    'defer' => FALSE,
    'group' => JS_LIBRARY,
    'every_page' => 1,
    'weight' => 20,
  );
}

/**
 * Implements hook_preprocess_html_tag().
 *
 * Inline JavaScript blocks must be executed in order. In the blocking script load,
 * this is the default behavior. With LAB, we must wrap them in wait() to preserve
 * this behavior
 */
function labjs_preprocess_html_tag(&$variables) {
  if (defined('LABJS_DISABLE')) {
    return;
  }

  if ($variables['element']['#tag'] == 'script' && !empty($variables['element']['#value']) && strpos($variables['element']['#value'], LABJS_EXCLUDE) !== 0) {
    $variables['element']['#value'] = "\$LAB.queue(function() {\n" . $variables['element']['#value'] . "\n});";
  }
}

/**
 * Helper for search for LAB.min.js file.
 *
 * If our system does not have libraries module, that file must reside at
 * sites/all/libraries/labjs/LAB.min.js.
 * If Libraries API is available, there are more choices.
 */
function labjs_get_path() {
  return (module_exists('libraries') ? libraries_get_path('labjs') : 'sites/all/libraries/labjs') . '/LAB.min.js';
}
